// Strings for the verification features, three-stage journeys and new roles.
// Merged over the base dictionary in i18n.jsx.

export const extra = {
  ar: {
    role_company: 'مشرف جهة التدريب',
    hint_start: 'أول مرة — لم يقدّم بعد',
    hint_middle: 'في منتصف التدريب',
    hint_end: 'في نهاية التدريب',
    hint_ineligible: 'غير مؤهل للتقديم',
    loginStudents: 'الطلاب',
    loginStaff: 'الجامعة وجهة التدريب',

    nav_interns: 'المتدربون',
    nav_code: 'رمز الحضور',
    nav_students: 'طلابي',
    nav_verification: 'مركز التحقق',
    status_active: 'بدأ التدريب',
    status_completed: 'مكتمل',
    companyRejectedNote: 'اعتذرت جهة التدريب عن الاستقبال — يلزم إعادة التوزيع',

    stage_new: 'طالب جديد',
    stage_active: 'قيد التدريب',
    stage_final: 'نهاية التدريب',
    stage_done: 'مكتمل',

    tab_overview: 'نظرة عامة',
    tab_logs: 'السجل اليومي',
    tab_reports: 'التقارير والتقييم',
    tab_audit: 'سجل الإجراءات',
    pendingCompanyBanner: 'تم توزيعك على {company}. بانتظار موافقة جهة التدريب على استقبالك.',
    companySup: 'مشرف جهة التدريب',
    plan: 'الخطة التدريبية',
    planText: 'الأسبوعان 1–2: التعرف على الفريق والأدوات · 3–5: مهام تصميم على مشاريع حقيقية · 6–8: مشروع ختامي وعرضه',

    att_title: 'حضور اليوم',
    att_notYet: 'لم تسجّل حضورك اليوم بعد',
    att_in: 'سُجّل الحضور الساعة {time}',
    att_out: 'انصراف {time} · {hours} ساعة حضور',
    att_codeLabel: 'رمز الحضور المعروض في جهة التدريب',
    att_scanHint: 'في التطبيق الفعلي يمسح الطالب رمز QR بكاميرا هاتفه؛ هنا نُدخل الرقم.',
    att_checkin: 'تسجيل الحضور',
    att_checkout: 'تسجيل الانصراف',
    att_invalid: 'الرمز غير صالح أو انتهت صلاحيته',
    att_location: 'داخل نطاق موقع جهة التدريب (محاكاة GPS)',
    att_rate: 'نسبة الحضور',
    att_done: 'اكتمل تسجيل اليوم',
    att_ended: 'انتهت فترة التدريب',

    hv_title: 'التحقق من الساعات',
    hv_counted: 'موثّقة ومحتسبة',
    hv_pending: 'بانتظار التحقق',
    hv_cut: 'غير محتسبة',
    hv_claimed: 'مُدّعاة',
    hv_required: 'المطلوب',
    hv_rule: 'لا تُحتسب أي ساعة إلا إذا طابقت الحضور المسجّل، وأكّدتها جهة التدريب، واعتمدها المشرف الأكاديمي.',

    log_day: 'يوم الحضور',
    log_attendedN: '{date} — حضور {h} ساعة',
    log_noDays: 'لا توجد أيام حضور مكتملة بدون سجل. سجّل حضورك وانصرافك أولًا.',
    log_warnExceeds: '⚠ أكثر من مدة حضورك المسجلة ({h} ساعة). سيُعلَّم السجل ولن يُحتسب الفرق.',
    log_onlyAttended: 'يمكن التسجيل فقط لأيام فيها حضور وانصراف مسجّلان.',

    tc_attendance: 'الحضور',
    tc_company: 'جهة التدريب',
    tc_academic: 'المشرف',
    ls_verified: 'موثّق',
    ls_awaiting_company: 'بانتظار جهة التدريب',
    ls_awaiting_academic: 'بانتظار المشرف',
    ls_rejected: 'مرفوض',
    counted_of: 'احتُسب {c} من {h} ساعة',
    disputeReasonLabel: 'سبب الاعتراض',

    f_no_attendance: 'لا يوجد تسجيل حضور في هذا اليوم',
    f_exceeds: 'الساعات المُدّعاة ({claimed}) أكثر من الحضور الفعلي ({attended})',
    f_geo: 'سُجّل الحضور من خارج موقع جهة التدريب',
    f_weekend: 'يوم عطلة رسمية',
    f_over_limit: 'أكثر من 10 ساعات في يوم واحد',
    f_late: 'سُجّل بعد {days} أيام من تاريخه',
    f_duplicate: 'نص المهام مطابق لسجل {date}',

    confirm: 'تأكيد',
    dispute: 'اعتراض',
    defaultDispute: 'الساعات المسجلة لا تطابق ما لاحظناه',
    co_newTitle: 'طلاب جدد بانتظار موافقتك',
    co_activeTitle: 'قيد التدريب — المتابعة اليومية',
    co_finalTitle: 'نهاية التدريب — التقييم',
    co_accept: 'قبول استقبال الطالب',
    co_reject: 'اعتذار عن الاستقبال',
    co_logsToConfirm: 'سجلات بانتظار تأكيدك',
    co_nothing: 'لا يوجد شيء بانتظارك',
    co_present: 'حاضر منذ {time}',
    co_absent: 'لم يسجّل حضوره اليوم',
    co_left: 'انصرف {time}',
    gpa: 'المعدل',
    code_title: 'رمز الحضور اليوم',
    code_hint: 'تُعرض هذه الشاشة عند مدخل الشركة. يتغير الرمز كل 30 ثانية، فلا يمكن تصويره وإرساله لطالب غائب.',
    code_expires: 'يتغير خلال {s} ث',
    code_todayList: 'سجل حضور اليوم',
    code_none: 'لم يسجّل أحد حضوره بعد',

    eval_student: 'تقييم الطالب',
    eval_submit: 'اعتماد التقييم',
    eval_done: 'تم التقييم: {score}%',
    pc_commitment: 'الالتزام والانضباط',
    pc_skills: 'المهارات الفنية',
    pc_teamwork: 'العمل ضمن فريق',
    pc_communication: 'التواصل',
    pc_initiative: 'المبادرة وحل المشكلات',
    ac_knowledge: 'تطبيق المعرفة الأكاديمية',
    ac_reports: 'جودة التقارير والتوثيق',
    ac_growth: 'التطور المهني خلال التدريب',

    sv_newStudent: 'طالب جديد تحت إشرافك',
    sv_waitingCompany: 'بانتظار موافقة جهة التدريب',
    sv_logsToApprove: 'سجلات بانتظار اعتمادك',
    sv_awaitingCompanyN: '{n} سجل بانتظار تأكيد جهة التدريب أولًا',
    sv_weekly: 'التقارير الأسبوعية',
    sv_visits: 'الزيارات الميدانية',
    sv_addVisit: 'تسجيل زيارة ميدانية',
    visit_date: 'تاريخ الزيارة',
    visit_status: 'حالة الطالب',
    visit_notes: 'الملاحظات',
    visit_recs: 'التوصيات',
    visit_excellent: 'ممتاز',
    visit_good: 'جيد',
    visit_attention: 'بحاجة إلى متابعة',
    sv_finalReport: 'التقرير النهائي',
    sv_reportGrade: 'درجة التقرير (من 100)',
    sv_approveFinal: 'اعتماد التقرير والدرجة',
    sv_noFinal: 'لم يرفع الطالب التقرير النهائي بعد',
    sv_evalTitle: 'التقييم الأكاديمي',

    rep_weekly: 'تقرير أسبوعي',
    rep_week: 'الأسبوع {n}',
    rep_final: 'التقرير النهائي',
    rep_submit: 'رفع التقرير',
    rep_placeholder: 'ماذا أنجزت هذا الأسبوع؟ ماذا تعلمت؟ ما التحديات؟',
    rep_finalPlaceholder: 'ملخص التدريب، المشاريع، المهارات المكتسبة، والتوصيات',
    rep_pending: 'بانتظار المراجعة',
    rep_approved: 'معتمد',
    rep_returned: 'مُعاد للتعديل',
    rep_finalLocked: 'يُفتح التقرير النهائي في نهاية التدريب',
    rateCompany: 'قيّم جهة التدريب',
    rateComment: 'ملاحظاتك (اختياري)',
    rateSubmit: 'إرسال التقييم',
    rated: 'شكرًا، تم إرسال تقييمك ({rating}/5)',
    myChecklist: 'متطلبات إتمام التدريب',

    c_hours: 'الساعات الموثقة مكتملة',
    c_attendance: 'نسبة الحضور 90% فأكثر',
    c_pending: 'لا توجد سجلات معلّقة',
    c_weekly: 'اعتماد جميع التقارير الأسبوعية',
    c_visits: 'اكتمال الزيارات الميدانية',
    c_final: 'اعتماد التقرير النهائي',
    c_eval_provider: 'تقييم جهة التدريب للطالب',
    c_eval_academic: 'تقييم المشرف الأكاديمي',
    c_eval_student: 'تقييم الطالب لجهة التدريب',

    audit_title: 'سجل الإجراءات المحمي',
    audit_hint: 'كل إجراء يُسجَّل مع صاحبه ووقته، ويرتبط ببصمة (hash) الإجراء الذي قبله. أي تعديل لاحق يكسر السلسلة ويُكتشف فورًا.',
    audit_check: 'فحص سلامة السجل',
    audit_ok: 'السجل سليم: {n} إجراء متسلسل دون أي تعديل',
    audit_broken: 'تم اكتشاف تلاعب',
    issue_chain: 'الإجراء رقم {i} ({at}) عُدّل بعد تسجيله — بصمته لا تطابق السلسلة',
    issue_mismatch: 'ساعات سجل {date} تغيّرت من {recorded} إلى {now} خارج النظام',
    audit_showAll: 'عرض كل الإجراءات ({n})',
    audit_fingerprint: 'بصمة السجل الحالية',
    a_applied: 'قدّم طلب التدريب',
    a_app_under_review: 'بدأ مراجعة الطلب',
    a_app_accepted: 'قبِل الطلب',
    a_app_rejected: 'رفض الطلب',
    a_app_needs_changes: 'طلب تعديلات على الطلب',
    a_assigned: 'وزّع الطالب وعيّن المشرف الأكاديمي',
    a_company_accepted: 'وافق على استقبال الطالب',
    a_checkin: 'سجّل الحضور ({time})',
    a_checkout: 'سجّل الانصراف ({time})',
    a_log_submitted: 'أضاف سجل يوم {date} ({hours} ساعة)',
    a_log_confirmed: 'أكّد سجل {date}',
    a_log_disputed: 'اعترض على سجل {date}',
    a_log_approved: 'اعتمد سجل {date}',
    a_log_returned: 'أعاد سجل {date}',
    a_report_submitted: 'رفع تقرير الأسبوع {week}',
    a_report_approved: 'اعتمد تقرير الأسبوع {week}',
    a_report_returned: 'أعاد تقرير الأسبوع {week}',
    a_final_submitted: 'رفع التقرير النهائي',
    a_final_approved: 'اعتمد التقرير النهائي ({grade}%)',
    a_final_returned: 'أعاد التقرير النهائي',
    a_visit: 'سجّل زيارة ميدانية ({date})',
    a_eval_provider: 'قيّم الطالب ({score}%)',
    a_eval_academic: 'قيّم الطالب أكاديميًا ({score}%)',
    a_eval_student: 'قيّم جهة التدريب ({rating}/5)',
    a_cert_issued: 'أصدر الشهادة {id}',

    vc_title: 'مركز التحقق',
    vc_sub: 'نزاهة الساعات التدريبية على مستوى الجامعة',
    vc_verifiedPct: 'من الساعات المُدّعاة موثّقة',
    vc_flagsByType: 'التنبيهات حسب النوع',
    vc_table: 'سجلات معلَّمة تحتاج انتباهًا',
    vc_attended: 'الحضور الفعلي',
    vc_claimed: 'المُدّعى',
    vc_flags: 'التنبيهات',
    vc_integrityTitle: 'سلامة السجلات',
    vc_scanAll: 'فحص سلامة جميع السجلات',
    vc_allOk: 'جميع السجلات سليمة: {n} ملف تدريب، {m} إجراء',
    vc_tamper: '🧪 محاكاة تلاعب بقاعدة البيانات',
    vc_tamperHint: 'تغيّر ساعات سجل معتمد إلى 9 وتعدّل أثره في سجل الإجراءات أيضًا، كما قد يفعل شخص لديه وصول مباشر لقاعدة البيانات.',
    vc_tampered: 'تم تعديل سجل يزن مباشرة في قاعدة البيانات. شغّل الفحص الآن.',
    vc_undo: 'التراجع عن المحاكاة',
    vc_liveNote: 'بيانات الجامعة + ملفات العرض الحية',

    cert_signed: 'موقّعة رقميًا من الجامعة (ECDSA)',
    cert_fingerprint: 'بصمة سجل التدريب',
    cert_tamperTest: '🧪 جرّب تزوير الدرجة',
    cert_tamperHint: 'يفتح صفحة التحقق بعد تغيير الدرجة في الرابط إلى 99%',
    v_checking: 'جارٍ التحقق من التوقيع الرقمي…',
    v_valid: 'التوقيع الرقمي للجامعة صالح — البيانات أصلية ولم تُعدّل',
    v_forged: 'تحذير: الشهادة مزوّرة أو معدّلة',
    v_forgedDetail: 'البيانات المعروضة لا تطابق التوقيع الرقمي للجامعة، فلا يُعتمد عليها.',
    v_hoursNote: 'ساعة موثّقة بالحضور وتأكيد جهة التدريب واعتماد المشرف الأكاديمي',
    v_key: 'مفتاح التحقق العام للجامعة',
    stat_verifiedHours: 'ساعات موثّقة هذا الفصل',
    close: 'إغلاق',
    cancel: 'إلغاء',
  },
  en: {
    role_company: 'Training provider supervisor',
    hint_start: 'First time — hasn’t applied',
    hint_middle: 'Mid-training',
    hint_end: 'End of training',
    hint_ineligible: 'Not eligible',
    loginStudents: 'Students',
    loginStaff: 'University & training provider',

    nav_interns: 'Interns',
    nav_code: 'Attendance code',
    nav_students: 'My students',
    nav_verification: 'Verification center',
    status_active: 'Training started',
    status_completed: 'Completed',
    companyRejectedNote: 'The training provider declined — reassign',

    stage_new: 'New',
    stage_active: 'In training',
    stage_final: 'Final stage',
    stage_done: 'Completed',

    tab_overview: 'Overview',
    tab_logs: 'Daily log',
    tab_reports: 'Reports & evaluation',
    tab_audit: 'Audit trail',
    pendingCompanyBanner: 'You were assigned to {company}. Waiting for the training provider to accept you.',
    companySup: 'Provider supervisor',
    plan: 'Training plan',
    planText: 'Weeks 1–2: onboarding & tools · 3–5: design tasks on real projects · 6–8: capstone project & presentation',

    att_title: "Today's attendance",
    att_notYet: "You haven't checked in today",
    att_in: 'Checked in at {time}',
    att_out: 'Checked out {time} · {hours} h on site',
    att_codeLabel: 'Attendance code shown at the provider',
    att_scanHint: 'In the real app the student scans the QR with their phone camera; here we type the number.',
    att_checkin: 'Check in',
    att_checkout: 'Check out',
    att_invalid: 'Invalid or expired code',
    att_location: 'Inside the provider’s location (simulated GPS)',
    att_rate: 'Attendance rate',
    att_done: "Today's attendance complete",
    att_ended: 'Training period ended',

    hv_title: 'Hours verification',
    hv_counted: 'Verified & counted',
    hv_pending: 'Awaiting verification',
    hv_cut: 'Not counted',
    hv_claimed: 'Claimed',
    hv_required: 'Required',
    hv_rule: 'An hour only counts if it matches recorded attendance, is confirmed by the training provider, and approved by the academic supervisor.',

    log_day: 'Attendance day',
    log_attendedN: '{date} — {h} h on site',
    log_noDays: 'No completed attendance days without a log. Check in and out first.',
    log_warnExceeds: '⚠ More than your recorded attendance ({h} h). The log will be flagged and the difference not counted.',
    log_onlyAttended: 'You can only log days with a recorded check-in and check-out.',

    tc_attendance: 'Attendance',
    tc_company: 'Provider',
    tc_academic: 'Supervisor',
    ls_verified: 'Verified',
    ls_awaiting_company: 'Awaiting provider',
    ls_awaiting_academic: 'Awaiting supervisor',
    ls_rejected: 'Rejected',
    counted_of: '{c} of {h} h counted',
    disputeReasonLabel: 'Dispute reason',

    f_no_attendance: 'No attendance recorded that day',
    f_exceeds: 'Claimed hours ({claimed}) exceed actual attendance ({attended})',
    f_geo: 'Checked in from outside the provider’s location',
    f_weekend: 'Official day off',
    f_over_limit: 'More than 10 hours in one day',
    f_late: 'Logged {days} days after the date',
    f_duplicate: 'Task text identical to the log of {date}',

    confirm: 'Confirm',
    dispute: 'Dispute',
    defaultDispute: "Logged hours don't match what we observed",
    co_newTitle: 'New students awaiting your approval',
    co_activeTitle: 'In training — daily follow-up',
    co_finalTitle: 'End of training — evaluation',
    co_accept: 'Accept student',
    co_reject: 'Decline',
    co_logsToConfirm: 'Logs awaiting your confirmation',
    co_nothing: 'Nothing waiting for you',
    co_present: 'On site since {time}',
    co_absent: 'Not checked in today',
    co_left: 'Left at {time}',
    gpa: 'GPA',
    code_title: "Today's attendance code",
    code_hint: 'Shown at the company entrance. The code changes every 30 seconds, so it can’t be photographed and sent to an absent student.',
    code_expires: 'Changes in {s}s',
    code_todayList: "Today's check-ins",
    code_none: 'Nobody has checked in yet',

    eval_student: 'Evaluate the student',
    eval_submit: 'Submit evaluation',
    eval_done: 'Evaluated: {score}%',
    pc_commitment: 'Commitment & punctuality',
    pc_skills: 'Technical skills',
    pc_teamwork: 'Teamwork',
    pc_communication: 'Communication',
    pc_initiative: 'Initiative & problem solving',
    ac_knowledge: 'Applying academic knowledge',
    ac_reports: 'Quality of reports',
    ac_growth: 'Professional growth',

    sv_newStudent: 'New student under your supervision',
    sv_waitingCompany: 'Waiting for provider approval',
    sv_logsToApprove: 'Logs awaiting your approval',
    sv_awaitingCompanyN: '{n} logs awaiting provider confirmation first',
    sv_weekly: 'Weekly reports',
    sv_visits: 'Field visits',
    sv_addVisit: 'Record a field visit',
    visit_date: 'Visit date',
    visit_status: 'Student status',
    visit_notes: 'Notes',
    visit_recs: 'Recommendations',
    visit_excellent: 'Excellent',
    visit_good: 'Good',
    visit_attention: 'Needs follow-up',
    sv_finalReport: 'Final report',
    sv_reportGrade: 'Report grade (out of 100)',
    sv_approveFinal: 'Approve report & grade',
    sv_noFinal: "The student hasn't submitted the final report yet",
    sv_evalTitle: 'Academic evaluation',

    rep_weekly: 'Weekly report',
    rep_week: 'Week {n}',
    rep_final: 'Final report',
    rep_submit: 'Submit report',
    rep_placeholder: 'What did you achieve this week? What did you learn? Challenges?',
    rep_finalPlaceholder: 'Training summary, projects, skills gained and recommendations',
    rep_pending: 'Awaiting review',
    rep_approved: 'Approved',
    rep_returned: 'Returned',
    rep_finalLocked: 'The final report opens at the end of training',
    rateCompany: 'Rate the training provider',
    rateComment: 'Your comments (optional)',
    rateSubmit: 'Submit rating',
    rated: 'Thanks, your rating was sent ({rating}/5)',
    myChecklist: 'Completion requirements',

    c_hours: 'Verified hours complete',
    c_attendance: 'Attendance of 90% or more',
    c_pending: 'No pending logs',
    c_weekly: 'All weekly reports approved',
    c_visits: 'Field visits completed',
    c_final: 'Final report approved',
    c_eval_provider: 'Provider evaluation of student',
    c_eval_academic: 'Academic supervisor evaluation',
    c_eval_student: 'Student rating of provider',

    audit_title: 'Tamper-evident audit trail',
    audit_hint: 'Every action is recorded with who did it and when, and chained to the hash of the previous action. Any later edit breaks the chain and is detected immediately.',
    audit_check: 'Check integrity',
    audit_ok: 'Record intact: {n} chained actions, no modifications',
    audit_broken: 'Tampering detected',
    issue_chain: 'Action #{i} ({at}) was modified after it was recorded — its hash no longer matches the chain',
    issue_mismatch: 'Hours of the {date} log changed from {recorded} to {now} outside the system',
    audit_showAll: 'Show all actions ({n})',
    audit_fingerprint: 'Current record fingerprint',
    a_applied: 'Applied for training',
    a_app_under_review: 'Started reviewing the application',
    a_app_accepted: 'Accepted the application',
    a_app_rejected: 'Rejected the application',
    a_app_needs_changes: 'Requested changes',
    a_assigned: 'Assigned the student & academic supervisor',
    a_company_accepted: 'Accepted the student',
    a_checkin: 'Checked in ({time})',
    a_checkout: 'Checked out ({time})',
    a_log_submitted: 'Logged {date} ({hours} h)',
    a_log_confirmed: 'Confirmed log of {date}',
    a_log_disputed: 'Disputed log of {date}',
    a_log_approved: 'Approved log of {date}',
    a_log_returned: 'Returned log of {date}',
    a_report_submitted: 'Submitted week {week} report',
    a_report_approved: 'Approved week {week} report',
    a_report_returned: 'Returned week {week} report',
    a_final_submitted: 'Submitted the final report',
    a_final_approved: 'Approved the final report ({grade}%)',
    a_final_returned: 'Returned the final report',
    a_visit: 'Recorded a field visit ({date})',
    a_eval_provider: 'Evaluated the student ({score}%)',
    a_eval_academic: 'Academic evaluation ({score}%)',
    a_eval_student: 'Rated the provider ({rating}/5)',
    a_cert_issued: 'Issued certificate {id}',

    vc_title: 'Verification center',
    vc_sub: 'Integrity of training hours across the university',
    vc_verifiedPct: 'of claimed hours verified',
    vc_flagsByType: 'Flags by type',
    vc_table: 'Flagged logs needing attention',
    vc_attended: 'Attended',
    vc_claimed: 'Claimed',
    vc_flags: 'Flags',
    vc_integrityTitle: 'Record integrity',
    vc_scanAll: 'Check integrity of all records',
    vc_allOk: 'All records intact: {n} training records, {m} actions',
    vc_tamper: '🧪 Simulate database tampering',
    vc_tamperHint: 'Changes an approved log to 9 hours and rewrites its audit entry too — as someone with direct database access might.',
    vc_tampered: "Yazan's record was edited directly in the database. Run the check now.",
    vc_undo: 'Undo simulation',
    vc_liveNote: 'University data + live demo records',

    cert_signed: 'Digitally signed by the university (ECDSA)',
    cert_fingerprint: 'Training record fingerprint',
    cert_tamperTest: '🧪 Try forging the grade',
    cert_tamperHint: 'Opens the verify page after changing the grade in the link to 99%',
    v_checking: 'Checking the digital signature…',
    v_valid: "The university's digital signature is valid — data is authentic and unmodified",
    v_forged: 'Warning: forged or modified certificate',
    v_forgedDetail: "The data shown does not match the university's digital signature. Do not rely on it.",
    v_hoursNote: 'hours verified by attendance, provider confirmation and academic approval',
    v_key: "University's public verification key",
    stat_verifiedHours: 'Verified hours this semester',
    close: 'Close',
    cancel: 'Cancel',
  },
}

// Short flag names for charts
Object.assign(extra.ar, {
  fs_exceeds: 'ساعات أكثر من الحضور', fs_no_attendance: 'بلا تسجيل حضور', fs_weekend: 'يوم عطلة',
  fs_geo: 'خارج موقع الشركة', fs_duplicate: 'نص مكرر', fs_late: 'تسجيل متأخر', fs_over_limit: 'أكثر من 10 ساعات',
})
Object.assign(extra.en, {
  fs_exceeds: 'Exceeds attendance', fs_no_attendance: 'No attendance', fs_weekend: 'Day off',
  fs_geo: 'Outside location', fs_duplicate: 'Duplicate text', fs_late: 'Late entry', fs_over_limit: 'Over 10 hours',
})

// Eligibility rules owned by the academic supervisor
Object.assign(extra.ar, {
  nav_rules: 'شروط الأهلية',
  rules_title: 'شروط الأهلية للتدريب حسب التخصص',
  rules_sub: 'يحدد المشرف الأكاديمي شروط التقديم لكل تخصص، ويطبّقها النظام تلقائيًا على جميع فرص التدريب فور الحفظ.',
  rules_minHours: 'الحد الأدنى من الساعات المعتمدة',
  rules_minGpa: 'الحد الأدنى للمعدل',
  rules_courses: 'مواد يجب النجاح فيها',
  rules_block: 'منع من لديه تدريب سابق غير مكتمل',
  rules_save: 'حفظ الشروط',
  rules_saved: 'تم الحفظ وتطبيق الشروط فورًا',
  rules_updated: 'آخر تعديل: {name} · {at}',
  rules_setBy: 'شروط تخصص {major} يحددها {name}',
  rules_preview: 'أثر الشروط على طلاب التخصص',
  rules_eligibleN: '{n} من {total} مؤهلون',
  rules_log: 'سجل تعديلات الشروط',
  rules_logEntry: '{name} عدّل شروط {major}',
  reason_gpa: 'معدلك ({have}) أقل من الحد الأدنى ({need})',
})
Object.assign(extra.en, {
  nav_rules: 'Eligibility rules',
  rules_title: 'Training eligibility rules by major',
  rules_sub: 'The academic supervisor sets the application conditions for each major; the system applies them to every opportunity as soon as they are saved.',
  rules_minHours: 'Minimum completed credit hours',
  rules_minGpa: 'Minimum GPA',
  rules_courses: 'Courses that must be passed',
  rules_block: 'Block students with an incomplete previous training',
  rules_save: 'Save rules',
  rules_saved: 'Saved and applied immediately',
  rules_updated: 'Last changed: {name} · {at}',
  rules_setBy: '{major} rules are set by {name}',
  rules_preview: 'Effect on students of this major',
  rules_eligibleN: '{n} of {total} eligible',
  rules_log: 'Rule change history',
  rules_logEntry: '{name} changed the {major} rules',
  reason_gpa: 'Your GPA ({have}) is below the minimum ({need})',
})
